services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  favorite-movies-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
